# Generated by Django 3.2.8 on 2021-10-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Sugestoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugestao', models.TextField()),
                ('area_interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areainteresse')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40)),
                ('resposta', models.TextField()),
                ('area_interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areainteresse')),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.links')),
            ],
        ),
        migrations.AddField(
            model_name='areainteresse',
            name='secretaria_relacionada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.secretaria'),
        ),
    ]
