# Generated by Django 3.2.8 on 2021-10-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaria',
            name='nome',
            field=models.CharField(default='teste', max_length=30),
            preserve_default=False,
        ),
    ]
