# Generated by Django 3.2.8 on 2021-10-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_secretaria_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name_plural': 'Questões'},
        ),
        migrations.AlterModelOptions(
            name='sugestoes',
            options={'verbose_name_plural': 'Sugestões'},
        ),
        migrations.AlterField(
            model_name='areainteresse',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questao',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
