# Generated by Django 3.2.8 on 2021-10-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211023_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalavrasChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='questao',
            name='palavras_chave',
            field=models.ManyToManyField(to='app.PalavrasChave'),
        ),
    ]
