# Generated by Django 3.2.8 on 2021-10-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211023_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questao',
            old_name='palavras_chave',
            new_name='palavraschave',
        ),
    ]
