# Generated by Django 3.2.8 on 2021-10-23 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_novidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novidade',
            name='links',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.links'),
        ),
    ]
